project:
  environment: pro
  name: aquarium

spring:
  security:
    user:
      name: scau
      password: 123456
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/aquarium?useUnicode=true&&useSSL=false&serverTimezone=GMT%2B8&&allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 1800000 #缓存过期时间，单位毫秒
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: pro
    group:
      #开发环境
      "dev": dev
      #生产环境
      "pro": pro
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表

jwt:
  secret_key: examboost134762168
  expiration_time: 259200

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.scau.client.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token_exclude:
  path: /error,/actuator,/swagger-ui.html,/swagger-resources,/webjars,/v2,/v3,/doc.html,/favicon.ico,/csrf,/image,/account

custom: # 自定义http启动端口
  http-port: 8080
server:
  port: 8080    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。